export const INTELLIGENCE_MODES = [
  "Ultra Automation - Experience S.H.I.E.L.D. AI Massive Potential",
  "Analytics - Analysis & Analytics AI insights",
  "Agents - Discussion on Description, Features, Function",
  "Ask - Universal Question & Answer System",
  "3D Printing - Advanced 3D Modeling & Manufacturing",
  "Code - Software Development & Programming Assistance",
  "Command Center - Blanch S.H.I.E.L.D AI Ecosystem",
  "Conventional Modes - switch to Blanch S.H.I.E.L.D. AI Conventional &  Hologram & Metaverse Modes",
  "Creative Media - Universal Media Generation",
  "Daily Briefing - Daily Updates, Summaries & Reports",
  "Debug - Troubleshooting & Problem Resolution",
  "Deep Search - Real-time web search data and S.H.I.E.L.D AI Answers with enhance references",
  "Deep Thinking Mode - Deep reasoning Better More complex topics",
  "Divine Wisdom Mode - Most AHAYAH & YASHAYA Spirituality",
  "Educational Resources & Study Mode - Quizzes, Guided learning, and more",
  "Entertainment - Entertainment, Games, Holographic & Metaverse Experiences",
  "Face Recognition - Advanced Facial Recognition & Analysis",
  "Face Swaps - Advanced Face Swapping & Manipulation",
  "Financial Analysis - Financial Markets, Investment Insights & Portfolio Management",
  "Finance Mode - Finance, Banking, Trading",
  "Gaming - Game Development, Testing, Strategy & Optimization",
  "Hands Free Mode - S.H.I.E.L.D. AI takes care of everything for you",
  "Health - Medical Analysis, Wellness & Healthcare",
  "Hologram & Metaverse Mode - Immersive Holographic & Metaverse Experiences",
  "S.H.I.E.L.D. AI Virtual Touchless User Gesture Fusion Interface (VTUGFI) - Gesture-based Interaction designed to allow users to manipulate digital spaces without physical hardware.",
  "Image - Image Processing, Analysis & Generation",
  "Industrial - Industrial Systems & Automation",
  "Industries - All Industries, People, Nations",
  "Manufacturing - Production & Manufacturing Optimization",
  "Maps Grounding - Location Intel",
  "Orchestrator - System Orchestration & Automation Control",
  "Planning - Strategic Planning & Project Management",
  "Printing - Document & Print Management",
  "Quantum Sequence Mode - Ultimate Mode for all Task, and Very Large Research, Very Large Task, Sequence",
  "News - News, Events, Promotions, information",
  "Smart Home - Home Automation & IoT Control",
  "Software - Software Engineering & Architecture",
  "Speed Smart - Thinks Deeply or Quickly based on task",
  "System Monitor - System Health & Performance Monitoring",
  "Technical & Technology - AI, Data, Development, Engineering, Information Technology, Software",
  "Voice - Voice Recognition & Speech Processing",
  "Video - Video Processing, Analysis & Generation",
  "Watchman - Blanch S.H.I.E.L.D. AI Watchman Calling",
  "Weather Forecast - Dawn, Sunrise, Noon, Ninth Hour, Sunset, Dusk, Global Time & Weather"
  
];

export const ANALYTICS_CATEGORIES = [
  "Overall Analysis & Analytics",
  "Accounts Analysis & Analytics",
  "Advertising Analysis & Analytics",
  "Affiliate Products & Services Analysis & Analytics",
  "Affiliate Program Analysis & Analytics",
  "Affiliate Referrals Analysis & Analytic",
  "AHAYAH & YASHAYA Bible Study Analysis & Analytics",
  "Anomaly Detection Analysis & Analytics",
  "Appointments Schedules Analysis & Analytics",
  "AI Agents Analysis & Analytics",
  "AI Analysis & Analytics",
  "Assets Analysis & Analytics",
  "Asset Management Analysis & Analytics",
  "Assets Submission Analysis & Analytics",
  "Balances Analysis & Analytics",
  "Automations Analysis & Analytics",
  "Automotive Analysis & Analytics",
  "Avatar Analysis & Analytics",
  "Banking Analysis & Analytics",
  "Blocked Analysis & Analytics",
  "Books Analysis & Analytics",
  "Broadcast Analysis & Analytics",
  "Business Cards Analysis & Analytics",
  "Business Networks Analysis & Analytics",
  "Businesses Analysis & Analytics",
  "CAD Analysis & Analytics",
  "Careers Analysis & Analytics",
  "Charity Analysis & Analytics",
  "Chats Analysis & Analytics",
  "Cloud Analysis & Analytics",
  "Community Analysis & Analytics",
  "Coupons Analysis & Analytics",
  "CRM & ERP & Analysis & Analytics",
  "Code & Development Analysis & Analytics",
  "Communications Analysis & Analytics",
  "Compliance & KYC Analysis & Analytics",
  "Computer Processing & Data Analysis & Analytics",
  "Concerts Analysis & Analytics",
  "Conference Analysis & Analytics",
  "Conference Calls Analysis & Analytics",
  "Creative Generates Analysis & Analytics",
  "Creative Generates 1D-12D Analysis & Analytics",
  "Creative Generated Animations Analysis & Analytics",
  "Creative Generated Art Analysis & Analytics",
  "Creative Generated Audio Analysis & Analytics",
  "Creative Generated Bible Analysis & Analytics",
  "Creative Generated Books Analysis & Analytics",
  "Creative Generated Broadcast Analysis & Analytics",
  "Creative Generated CAD Analysis & Analytics",
  "Creative Generated Development Analysis & Analytics",
  "Creative Generated Image Analysis & Analytics",
  "Creative Generated Face Swaps Analysis & Analytics",
  "Creative Generated Films Analysis & Analytics",
  "Creative Generated Film Scripts Analysis & Analytics",
  "Creative Generated Games Analysis & Analytics",
  "Creative Generated Graphic Design Analysis & Analytics",
  "Creative Generated Media Analysis & Analytics",
  "Creative Generated Music Analysis & Analytics",
  "Creative Generated Operating Systems Analysis & Analytics",
  "Creative Generated Photography Analysis & Analytics",
  "Creative Generated Podcast Analysis & Analytics",
  "Creative Generated Sacred Texts Analysis & Analytics",
  "Creative Generated Software Analysis & Analytics",
  "Creative Generated Technology Analysis & Analytics",
  "Creative Generated Video Analysis & Analytics",
  "Creative Generated Web/App Analysis & Analytics",
  "Creative Genes / Genomics Analysis & Analytic",
  "Creative Media & Entertainment Analysis & Analytics",
  "Creators Calendar Analysis & Analytics",
  "Cybersecurity & Threat Analysis & Analytics",
  "Customer Lifetime Value (CLV) Analysis & Analytics",
  "Customer Churn & Retention Analysis & Analytics",
  "Daily Burnt Offerings Analysis & Analytics",
  "Daily Volume Analysis & Analytics",
  "DAG Performance Monitor Analysis & Analytics",
  "Data Analysis & Analytics",
  "Database Analysis & Analytics",
  "Data Market Insights Analysis & Analytics",
  "Data Pipeline/ETL Performance Analysis & Analytics",
  "Data Quality & Integrity Analysis & Analytics",
  "Decentralized Ledger (Blockchain) Analysis & Analytics",
  "Decision Support Systems Analysis & Analytics",
  "Deep Learning & Neural Network Analysis & Analytics",
  "Demographics & Psychographics Analysis & Analytics",
  "Deposits Analysis & Analytics",
  "Devices Analysis & Analytics",
  "Dietary & Health Analysis & Analytics",
  "Discipleship & Mentorship Analysis & Analytics",
  "Digital Assets Analysis & Analytics",
  "Digital Consumer Analysis & Analytics",
  "Discount Analysis & Analytics",
  "Dispute & Resolution Analysis & Analytics",
  "Distributed Ledger Technology Analysis & Analytics",
  "Distribution & Logistics Analysis & Analytics",
  "Documents Analysis & Analytics",
  "Document Management Analysis & Analytics",
  "Documentaries Analysis & Analytics",
  "Domains Analysis & Analytics",
  "Domain & Infrastructure Analysis & Analytics",
  "Drink Offerings Analysis & Analytics",
  "Drive Analysis & Analytics",
  "Dues & Contributions Analysis & Analytics",
  "E-Commerce & Storefront Analysis & Analytics",
  "Email Analysis & Analytics",
  "Ecosystem Analysis & Analytics",
  "Education Analysis & Analytics",
  "Educational & Learning Resource Analysis & Analytics",
  "Emancipation Bridging Funds Analysis & Analytics",
  "Engineering Analysis & Analytics",
  "Entertainment Analysis & Analytics",
  "Energy Analysis & Analytics",
  "Environmental/Impact Reporting Analysis & Analytics",
  "Events Analysis & Analytics",
  "Fasts Analysis & Analytics",
  "Feedback & Sentiment Analysis & Analytics",
  "Finance Analysis & Analytics",
  "Files Analysis & Analytics",
  "Financial Instruments Marketplace Analysis & Analytics",
  "Forecasts & Predictive Analysis & Analytics",
  "Fund Raising Analysis & Analytics",
  "Games Analysis & Analytics",
  "Gaming & Prizes Analysis & Analytics",
  "Gentiles Analysis & Analytics",
  "Global Markets Analysis & Analytics",
  "Global Network Analysis & Analytics",
  "GPU Analysis & Analytics",
  "Health Analysis & Analytics",
  "Hebrew Israelites/Yasharahla Analysis & Analytics",
  "High Priest Offerings Analysis & Analytics",
  "Hologram & Metaverse Analysis & Analytics",
  "Holy Days Analysis & Analytics",
  "Holy Fasts Analysis & Analytics",
  "Feasts Analysis & Analytics",
  "Homes Analysis & Analytics",
  "Hosting Analysis & Analytics",
  "Hospitality Analysis & Analytics",
  "Hotel Analysis & Analytics",
  "Humanitarian Fund Analysis & Analytics",
  "Human Resources/Talent Analysis & Analytics",
  "Industrial Analysis & Analytics",
  "Influencer Analysis & Analytics",
  "Insights Analysis & Analytics",
  "Investment Analysis & Analytics",
  "Legal & Regulatory Affairs Analysis & Analytics",
  "Laws & Commandments Analysis & Analytics",
  "LED Analysis & Analytics",
  "LLMs Analysis & Analytics",
  "Loans Analysis & Analytics",
  "Locations Analysis & Analytics",
  "Logistics Analysis & Analytics",
  "Machine to Machine Analysis & Analytics",
  "Market Cap Analysis & Analytics",
  "Marked & Red Flagged Analysis & Analytics",
  "Market Segmentation Analysis & Analytics",
  "Marketing & PR Analysis & Analytics",
  "Mobile Number Analysis & Analytics",
  "Networks Analysis & Analytics",
  "New Month Offerings Analysis & Analytics",
  "New Year Offerings Analysis & Analytics",
  "Notes Analysis & Analytics",
  "Notification Analysis & Analytics",
  "Passports Analysis & Analytics",
  "Peace Offerings Analytics",
  "Podcast Analysis & Analytics",
  "Private Equity Analysis & Analytics",
  "Planes Analysis & Analytics",
  "Prayers Analysis & Analytics",
  "Predictive Modeling (Forecasting) Analysis & Analytics",
  "Prizes Analysis & Analytics",
  "Products Analysis & Analytics",
  "Profitability Analysis & Analytics",
  "Prophecies Analysis & Analytics",
  "Projects Analysis & Analytics",
  "Published Analysis & Analytics",
  "RAM Analysis & Analytics",
  "Reminders Analysis & Analytics",
  "Reports Analysis & Analytics",
  "Real Estate Analysis & Analytics",
  "Restaurant Analysis & Analytics",
  "Rewards Analysis & Analytics",
  "Royal Priesthood Analysis & Analytics",
  "Sabbaths Analysis & Analytics",
  "Securities Analysis & Analytics",
  "Sentiment Analysis & Analytics",
  "Sacred Texts Analysis & Analytics",
  "Security Analysis & Analytics",
  "Schools Analysis & Analytics",
  "Server Analysis & Analytics",
  "Scheduling Appointments Analysis & Analytics",
  "Sin Offerings Analysis & Analytics",
  "Space Analysis & Analytic",
  "Standalone Electronic Wallets Card Analysis & Analytics",
  "Social Media Analysis & Analytics",
  "Storage Analysis & Analytics",
  "Services Analysis & Analytics",
  "Smart Cities Analysis & Analytics",
  "Sovereign Court Analysis & Analytics",
  "Sovereign Analysis & Analytics",
  "Studies Analysis & Analytics",
  "Supply Chain/Logistics Optimization Analysis & Analytics",
  "Swaps Analysis & Analytics",
  "Tabernacle Offerings Analysis & Analytics",
  "Tasks Analysis & Analytics",
  "Technology Analysis & Analytics",
  "Temple Offerings Analysis & Analytics",
  "Tournaments Analysis & Analytics",
  "Trades Analysis & Analytics",
  "Trading Analysis & Analytics",
  "Transactions Analysis & Analytics",
  "Transfers Analysis & Analytics",
  "Travels Analysis & Analytics",
  "Tokens & Tokenization Analysis & Analytics",
  "Transaction Per Second (TPS) Analysis & Analytics",
  "Trading Hub Analysis & Analytics",
  "Universal Analysis & Analytics",
  "Universal Business Networks",
  "Unintentional Sin Offerings",
  "Usage Analysis & Analytics",
  "Users Analysis & Analytics",
  "Videos Analysis & Analytics",
  "Video Conference Analysis & Analytics",
  "Ventures Analysis & Analytics",
  "Virtual Marketplaces Analysis & Analytics",
  "Virtual Tours Analysis & Analytics",
  "Warnings Analysis & Analytics",
  "Watchman Analysis & Analytics",
  "Wallets Analysis & Analytics",
  "Web & App Analysis & Analytics",
  "Web Traffic & User Experience (UX) Analysis & Analytics",
  "Withdraws Analysis & Analytics",
  "Writing Analysis & Analytics"
];

export const BEST_RECOMMENDATIONS = [
  "Best Automotive",
  "Best Benevolence & Gifts",
  "Best Blessings & Rewards",
  "Best Digital Assets",
  "Best Charity",
  "Best Humanitarian Fund",
  "Best Emancipation Fund",
  "Best Energy",
  "Best Financial Instruments Market Place",
  "Best Investments with ROI",
  "Best Holographic",
  "Best Investors",
  "Best Media & Entertainment",
  "Best Metaverse Tours",
  "Best Metaverse Shopping Experience",
  "Best Opportunities",
  "Best Promotions",
  "Best Discounts",
  "Best Rewards",
  "Best Real Estate",
  "Best Talents",
  "Best Trading",
  "Best Trends",
  "Best Virtual Marketplace"
];

export const HELP_CATEGORIES = [
  "Need Any Help?",
  "Need Advice?",
  "Need Alkaline Water?",
  "Need Asset Management?",
  "Need Assistant?",
  "Need Assistant to Pay Bills?",
  "Need Automotive?",
  "Need Benevolence & Gifts?",
  "Need Brand Ambassador?",
  "Need Banking?",
  "Need Charity?",
  "Need Commodities?",
  "Need Creative Media Content?",
  "Need Deep Research?",
  "Need Discounts?",
  "Need Emancipation Bridging Funds?",
  "Need Energy?",
  "Need Entertainment?",
  "Need Events?",
  "Need Expedite Delivery?",
  "Need Food?",
  "Need Financing?",
  "Need Health?",
  "Need Hologram?",
  "Need Humanitarian Assistance?",
  "Need Home?",
  "Need Investment?",
  "Need Job or Career?",
  "Need Marketing?",
  "Need Media Content?",
  "Need Metaverse?",
  "Need Office Space?",
  "Need Operating Systems?",
  "Need Personal Driver?",
  "Need Product and/or Service?",
  "Need Project Funding?",
  "Need Real Estate?",
  "Need Research & Development",
  "Need Software?",
  "Need Sponsor?",
  "Need Special Promotions?",
  "Need Support?",
  "Need Trading?",
  "Need Transportation?",
  "Need Website/App?",
  "Need Assistant on Compliance & KYC?",
  "Need to List an Asset, Product and/or Service?",
  "Need to List on a Marketplace?",
  "Need to List on the Blanch Colonnade?",
  "Need to List on the Blanch Corridor?",
  "Need to List on the Blanch Network?",
  "Need to List on the Blanch Hadash Dabash?",
  "Need to List on the Blanch Infinity DLT?",
  "Need to List on the Blanch Group?",
  "Need to List on the Blanch S.H.I.E.L.D. AI?",
  "Need to List on the Metaverse?"
];
